# Generated by Django 2.2.19 on 2022-05-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220520_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='consist_of_ingredients', through='recipes.Recipe_to_ingredient', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe_to_ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
