# Generated by Django 2.2.19 on 2022-06-01 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220531_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipes',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='ingredient_must_be_unique_in_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(pub_date__gte=django.db.models.functions.datetime.Now()), name='pub_date_must_be_greater_or_equal_than_today'),
        ),
    ]
