# Generated by Django 2.2.19 on 2022-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220523_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients_in_recipes',
            new_name='IngredientsInRecipes',
        ),
    ]
