# Generated by Django 2.2.19 on 2022-05-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь(я)', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
