# Generated by Django 2.2.19 on 2022-05-27 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220523_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
